channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python==3.7.8
  - numpy==1.19.4
  - pandas==1.1.4
  - plotly==4.12.0
  - bokeh==2.2.3
  - panel==0.10.1
  - jupyter-panel-proxy
  - autograd==1.3
  - matplotlib==3.3.3
  - jinja2=2.11.3
  - jupyter-server-proxy==3.2.2