channels:
   - plotly
   - bokeh
   - pyviz
   - conda-forge
dependencies:
  - python==3.7.8
  - numpy==1.19.4
  - pandas==1.1.4
  - plotly==4.12.0
  - panel==0.10.1
  - jupyter-panel-proxy
  - autograd==1.3
  - matplotlib==3.3.3
  - pip==20.2.4
  - pip:
    - jupyter-server-proxy