name: gd
channels:
  - pyviz
  - plotly
  - bokeh
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - anyio=3.6.2
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - attrs=22.2.0
  - autograd=1.3
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - bokeh=2.2.3
  - brotlipy=0.7.0
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.14.6
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - cryptography=38.0.2
  - cycler=0.11.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - flit-core=3.8.0
  - freetype=2.12.1
  - frozenlist=1.3.1
  - future=0.18.2
  - idna=3.4
  - importlib-metadata=4.11.4
  - importlib_resources=5.10.2
  - ipykernel=6.16.2
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=2.11.3
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter-panel-proxy=0.1.0
  - jupyter-server-proxy=1.0
  - jupyter_client=7.4.8
  - jupyter_core=4.11.1
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.2.2
  - kiwisolver=1.4.4
  - lcms2=2.14
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libffi=3.3
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libzlib=1.2.13
  - llvm-openmp=15.0.6
  - markdown=3.4.1
  - markupsafe=2.0.1
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - multidict=6.0.2
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.4.5
  - nbconvert-core=6.4.5
  - nbconvert-pandoc=6.4.5
  - nbformat=5.7.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numpy=1.19.4
  - openjpeg=2.5.0
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.1.4
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - panel=0.10.1
  - param=1.12.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - plotly=4.12.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pyct=0.4.8
  - pyct-core=0.4.8
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.7.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.7
  - pytz=2022.7
  - pyviz_comms=2.2.1
  - pyyaml=6.0
  - pyzmq=24.0.1
  - readline=8.1.2
  - requests=2.28.1
  - retrying=1.3.3
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=59.8.0
  - simpervisor=0.3
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - terminado=0.17.1
  - testpath=0.6.0
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.8.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.13
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
